### ISSUE TITLE
why try/catch is not supported?

### ISSUE THREAD

**Issue by mr-ma** [NethermindEth/warp#290]
I am testing some sample contracts and ran into try catch not supported issue:
```
Error: Warp does not support try catch
   --> node_modules/@openzeppelin/contracts/token/ERC721/ERC721.sol:378:15:
    |
378 |             } catch (bytes memory reason) {
    |               ^ (Relevant source part starts here and spans across multiple lines).
                                                                        ^ (Relevant source part starts here and spans across multiple lines).
```
My question is whether this is a matter of implementation or a limitation?

**Comment by swapnilraj** [comment]
This is a limitation and its caused by how failures are done on Starknet.
Currently on Starknet, there is no way to "catch" a failing assert thus warp also does not support this behaviour.
The workarounds for making try/catch work would cause degraded performance and a lot more complexity in the compiler. In the future we might consider adding support for try/catch.
