### ISSUE TITLE
Support for inline Yul assembly

### ISSUE THREAD

**Issue by DanieleDiBenedetto** [NethermindEth/warp#470]
Hi everyone, congratulations for the great project !
I noticed that, currently, inline Yul assembly is not supported, and I was wondering if you are thinking of introducing it.
Actually, I noticed that some work was already done some time ago in the `warp-yul` branch so, in case there is no upcoming plan to re-introduce this feature, how much difficult would it be to integrate the relevant content of the `warp-yul` branch in the current most up-to-date one (I guess it's `warp-ts`) ?
Thanks in advance !

**Comment by JorikSchellekens** [comment]
Hello @DanieleDiBenedetto! Thanks :)

We dropped inline assembly because we moved away from solidity's calldata semantics and in order to do this we no longer compile through YUL. There have been some discussions internally about how we could support YUL or something similar. There are a two proposals:

1. Support a subset of YUL by translating its semantics to our memory model. We'd have to drop any YUL related to calldata. The transpiled version may also have subtly different semantics and we'd have to be obnoxiously clear about what that is. Unfortunately warp-yul and the YUL work in main is not relevant at all to how this could be implemented for warp-ts.
2. Allow Cairo blocks, directly inlining Cairo could allow for much of the same behaviour and optimisation that the current inline assembly is used for.

There is no plan to include them at the moment and the discussion is slated for after the first release (hype) of warp-ts. If you're interested in tackling this please reach out to myself, @DomHenderson or @swapnilraj.

**Comment by swapnilraj** [comment]
Closing this issue, reach out to us if you're interested in the implementation.
