### ISSUE TITLE
Parameter List Writer

### ISSUE THREAD

**Issue by piwonskp** [NethermindEth/warp#936]

**Comment by cicr99** [comment]
Currently, return parameters are handled in this writer, but the syntax for them has changed. Now return parameters are not named and you either return a tuple (in which case, each type has to be specified) or a simple type. Since this is so different from the way input parameters are handled, the suggestion is to create another writer just for return parameters. I'll create a different issue for that.

**Comment by cicr99** [comment]
The issue for return parameters #950

**Comment by cicr99** [comment]
This issue was addressed on #983 and return parameters in #961
